/**
 * Curated, optimized salon photos. Files live in /public/images as
 * <name>-400.webp and <name>-800.webp (hero: -560 and -1000), generated by
 * scripts/process-photos.mjs.
 */
export interface SitePhoto {
  name: string
  alt: string
}

export const heroPhoto: SitePhoto = {
  name: 'hero',
  alt: 'Nude and white almond nails with rose gold glitter accents, styled by Beauty Nails Spa in Champaign',
}

/** Real photos of the salon and storefront. */
export const salonPhotos = {
  sign: { name: 'storefront-sign', alt: 'Beauty Nails Spa storefront sign in Champaign, Illinois' },
  door: {
    name: 'storefront-door',
    alt: 'Entrance to Beauty Nails Spa at 706 W Marketview Drive in Champaign, with business hours posted',
  },
  wall: { name: 'salon-wall', alt: 'Wall of nail polish colors inside Beauty Nails Spa' },
  pedicure: { name: 'salon-pedicure', alt: 'Comfortable pedicure chairs at Beauty Nails Spa in Champaign' },
  stations: { name: 'salon-stations', alt: 'Clean, modern manicure stations inside Beauty Nails Spa' },
} as const

/**
 * Real client work, used across the gallery, home and service pages.
 * Ordered to lead with the most premium, varied sets (home shows the first 8).
 * Alt text describes the actual design in each photo.
 */
export const galleryPhotos: SitePhoto[] = [
  { name: 'nails-02', alt: 'Black and gold glitter coffin nails with crystal accents by Beauty Nails Spa' },
  { name: 'nails-20', alt: 'Romantic nude and pink bridal nails with delicate white flowers' },
  { name: 'nails-21', alt: 'Red and white marble nails with a glossy rose-accented finish' },
  { name: 'nails-09', alt: 'Long white coffin nails with a smooth, polished finish' },
  { name: 'nails-10', alt: 'Long nails with colorful art and a soft white floral accent' },
  { name: 'nails-23', alt: 'Pink and yellow 3D flower nails with sparkling crystal accents' },
  { name: 'nails-01', alt: 'Soft pink and white French nails on a plush white background' },
  { name: 'nails-12', alt: 'Warm coral nails styled with autumn flowers' },
  { name: 'nails-08', alt: 'Playful rainbow tip nails with a glossy coat' },
  { name: 'nails-11', alt: 'Colorful nail art styled with fresh white hydrangeas' },
  { name: 'nails-13', alt: 'Rich burgundy nails with a high-shine finish' },
  { name: 'nails-18', alt: 'Coral and orange ombre coffin nails' },
  { name: 'nails-15', alt: 'Festive confetti nail art with soft floral accents' },
  { name: 'nails-05', alt: 'Neutral nails with a delicate hand-painted accent' },
  { name: 'nails-06', alt: 'Deep red French tip nails with a glossy finish' },
  { name: 'nails-07', alt: 'Pink and white nails with a clean, polished look' },
  { name: 'nails-14', alt: 'Long coffin nails with bright, bold custom nail art' },
  { name: 'nails-16', alt: 'Natural nude nails with a clean, classic shape' },
  { name: 'nails-17', alt: 'Black ombre nails on a soft white background' },
  { name: 'nails-19', alt: 'Red and orange tip nails styled with statement rings' },
  { name: 'nails-22', alt: 'Festive red French nails with hand-painted snowflake art' },
  { name: 'nails-04', alt: 'Nude pink nails with subtle accent detailing' },
  { name: 'nails-03', alt: 'Detailed pedicure with custom nail art on the toes' },
]

/** Stable, slug-based selection so each page shows a consistent set. */
export function photosForSlug(slug: string, count: number): SitePhoto[] {
  let h = 0
  for (let i = 0; i < slug.length; i++) h = (h * 31 + slug.charCodeAt(i)) >>> 0
  const n = galleryPhotos.length
  const stride = 1 + (h % (n - 1))
  const out: SitePhoto[] = []
  const used = new Set<number>()
  let idx = h % n
  while (out.length < Math.min(count, n)) {
    if (!used.has(idx)) {
      used.add(idx)
      out.push(galleryPhotos[idx])
    }
    idx = (idx + stride) % n
    if (used.size >= n) break
  }
  return out
}

export function photoForSlug(slug: string): SitePhoto {
  return photosForSlug(slug, 1)[0]
}
